# BTHome ESP32 Example Configuration
# Broadcasts sensor data via BLE using BTHome v2 protocol
# Compatible with Home Assistant's BTHome integration
#
# Supported boards: ESP32, ESP32-C3, ESP32-S3 (with ESP-IDF framework)

esphome:
  name: bthome-esp32
  friendly_name: BTHome ESP32 Sensor

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

external_components:
  - source:
      type: local
      path: components
    components: [bthome]

# Required for ESP32 BLE
esp32_ble:
  id: ble

#
# ========== SENSORS ==========
#

# Option 1: DHT22 temperature/humidity sensor
# sensor:
#   - platform: dht
#     pin: GPIO4
#     model: DHT22
#     temperature:
#       id: dht_temperature
#       name: "Temperature"
#     humidity:
#       id: dht_humidity
#       name: "Humidity"
#     update_interval: 30s

# Option 2: BME280 I2C sensor
# i2c:
#   sda: GPIO21
#   scl: GPIO22
#
# sensor:
#   - platform: bme280_i2c
#     address: 0x76
#     temperature:
#       id: bme_temperature
#       name: "Temperature"
#     humidity:
#       id: bme_humidity
#       name: "Humidity"
#     pressure:
#       id: bme_pressure
#       name: "Pressure"
#     update_interval: 30s

# Option 3: Template sensors (for testing)
sensor:
  - platform: template
    id: test_temperature
    name: "Temperature"
    unit_of_measurement: "°C"
    lambda: 'return 22.5;'
    update_interval: 30s

  - platform: template
    id: test_humidity
    name: "Humidity"
    unit_of_measurement: "%"
    lambda: 'return 55.0;'
    update_interval: 30s

  - platform: template
    id: test_battery
    name: "Battery"
    unit_of_measurement: "%"
    lambda: 'return 85.0;'
    update_interval: 60s

#
# ========== BINARY SENSORS ==========
#

binary_sensor:
  # PIR motion sensor
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLDOWN
    id: pir_motion
    name: "Motion"
    device_class: motion
    filters:
      - delayed_off: 30s

  # Door/window reed switch
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
    id: door_contact
    name: "Door"
    device_class: door

#
# ========== BTHOME CONFIGURATION ==========
#

bthome:
  # Advertising interval (20ms - 10240ms)
  min_interval: 5s
  max_interval: 10s

  # TX power: -12, -9, -6, -3, 0, 3, 6, 9 dBm
  tx_power: 3

  # Optional: Enable encryption (32 hex chars = 16 bytes)
  # Generate key: openssl rand -hex 16
  # encryption_key: "231d39c1d7cc1ab1aee224cd096db932"

  # Sensor measurements to broadcast
  # See https://bthome.io/format/ for full specification
  #
  # Supported sensor types:
  #   Basic: packet_id, battery, temperature, humidity, pressure, illuminance
  #   Mass: mass_kg, mass_lb
  #   Environment: dewpoint, co2, tvoc, pm2_5, pm10, moisture
  #   Electrical: voltage, current, power, energy
  #   Count: count_uint8, count_uint16, count_uint32, count_sint8, count_sint16, count_sint32
  #   Distance: distance_mm, distance_m
  #   Motion: rotation, speed, acceleration, gyroscope, direction
  #   Volume: volume_l_01, volume_ml, volume_l, volume_storage, volume_flow_rate, water, gas, gas_uint32
  #   Time: duration, timestamp
  #   Other: uv_index, conductivity, precipitation, channel, rotational_speed
  #   Alternate precision: humidity_uint8, moisture_uint8, temperature_01, voltage_01
  #   Extended power: energy_uint32, power_sint32, current_sint16
  #   Extended temp: temperature_sint8, temperature_sint8_035
  sensors:
    - type: temperature
      id: test_temperature
    - type: humidity
      id: test_humidity
    - type: battery
      id: test_battery

  # Binary sensor measurements to broadcast
  # See https://bthome.io/format/ for full specification
  #
  # Supported binary sensor types:
  #   generic_boolean, power, opening, battery_low, battery_charging
  #   carbon_monoxide, cold, connectivity, door, garage_door
  #   gas, heat, light, lock, moisture_binary, motion
  #   moving, occupancy, plug, presence, problem, running
  #   safety, smoke, sound, tamper, vibration, window
  binary_sensors:
    - type: motion
      id: pir_motion
      advertise_immediately: true  # Instant broadcast on state change
    - type: door
      id: door_contact
      advertise_immediately: true
