# BTHome Receiver Example - Bluedroid Stack (Default)
#
# Uses the standard Bluedroid BLE stack via esp32_ble_tracker.
# Compatible with other ESPHome BLE components (bluetooth_proxy, etc.).
#
# Use bthome_receiver_nimble.yaml for a lighter alternative if you
# don't need other BLE components.

esphome:
  name: bthome-receiver-bluedroid

esp32:
  variant: esp32
  framework:
    type: esp-idf

wifi:
  ap:
    ssid: "BTHome-Receiver"

captive_portal:

external_components:
- source:
    type: local
    path: components
  components: [ bthome_receiver ]

logger:
  level: DEBUG

# Required for Bluedroid mode
esp32_ble_tracker:
  scan_parameters:
    active: false

# BTHome Receiver Hub with Bluedroid (default)
bthome_receiver:
  ble_stack: bluedroid # Can be omitted, this is the default
  # Discovery mode: Enable to log all BTHome advertisements for finding devices
  # This will dump MAC addresses, sensor types, and values to the log
  # Disable after discovering your devices to reduce log spam
  # dump_interval: 30s  # Uncomment to enable periodic dumping
  devices:
  - mac_address: "AA:BB:CC:DD:EE:FF"
    name: "Living Room Sensor"
    # Optional: Add encryption key for encrypted devices
    # encryption_key: "231d39c1d7cc1ab1aee224cd096db932"

    # Receive temperature and humidity from BTHome device
sensor:
- platform: bthome_receiver
  mac_address: "AA:BB:CC:DD:EE:FF"
  temperature:
    name: "Living Room Temperature"
  humidity:
    name: "Living Room Humidity"
  battery:
    name: "Living Room Battery"

# Receive motion detection from BTHome device
binary_sensor:
- platform: bthome_receiver
  mac_address: "AA:BB:CC:DD:EE:FF"
  motion:
    name: "Living Room Motion"
  door:
    name: "Living Room Door"
