# BTHome Receiver Example - NimBLE Stack (Lightweight)
#
# Uses the lightweight NimBLE BLE stack for receive-only BTHome gateways.
# Saves ~253KB flash and ~10KB RAM compared to Bluedroid.
#
# Note: NimBLE cannot coexist with esp32_ble_tracker or bluetooth_proxy.
# Use bthome_receiver_bluedroid.yaml if you need those components.

esphome:
  name: bthome-receiver-nimble

esp32:
  variant: esp32s3
  framework:
    type: esp-idf # Required for NimBLE

wifi:
  ap:
    ssid: "BTHome-Receiver"

captive_portal:

external_components:
- source:
    type: local
    path: components
  components: [ bthome_receiver ]

logger:
  level: DEBUG

# BTHome Receiver Hub with NimBLE (lightweight, standalone)
bthome_receiver:
  ble_stack: nimble
  scan_interval: 50ms
  scan_window: 50ms
  # Discovery mode: Enable to log all BTHome advertisements for finding devices
  # This will dump MAC addresses, sensor types, and values to the log
  # Disable after discovering your devices to reduce log spam
  # dump_interval: 30s  # Uncomment to enable periodic dumping
  devices:
  - mac_address: "AA:BB:CC:DD:EE:FF"
    name: "Living Room Sensor"
    # Optional: Add encryption key for encrypted devices
    # encryption_key: "231d39c1d7cc1ab1aee224cd096db932"

    # Receive temperature and humidity from BTHome device
sensor:
- platform: bthome_receiver
  mac_address: "AA:BB:CC:DD:EE:FF"
  temperature:
    name: "Living Room Temperature"
  humidity:
    name: "Living Room Humidity"
  battery:
    name: "Living Room Battery"

# Receive motion detection from BTHome device
binary_sensor:
- platform: bthome_receiver
  mac_address: "AA:BB:CC:DD:EE:FF"
  motion:
    name: "Living Room Motion"
  door:
    name: "Living Room Door"
