# BTHome Button and Dimmer Event Example (Unified Event API)
# Demonstrates how to send button and dimmer events via BLE using BTHome v2 protocol
# Compatible with Home Assistant's BTHome integration
#
# BTHome v2 Spec: https://bthome.io/format/
# Multiple buttons are represented by multiple sequential 0x3A objects
# The order determines button index (0=first, 1=second, etc.)

esphome:
  name: bthome-button-dimmer
  friendly_name: BTHome Button Dimmer
  on_boot:
    - priority: -100
      then:
        - logger.log: "BTHome ready with unified event API."

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

wifi:
  ap: {}

external_components:
- source:
    type: local
    path: components
  components: [ bthome ]

# Required for ESP32 BLE
esp32_ble:
  id: ble

# BTHome configuration
bthome:
  id: bthome_broadcaster
  min_interval: 5s
  max_interval: 10s
  tx_power: 0
  trigger_based: true  # For button/event-based devices
  max_events: 4

# Example button that triggers BTHome button events using actions
binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    inverted: true
    mode:
      input: true
      pullup: true
  name: "Button 0"
  on_press:
    then:
      - logger.log: "Button 0 pressed - sending BTHome button event"
      # Using the new bthome.button_event action
      - bthome.button_event:
          id: bthome_broadcaster
          index: 0
          action: 0x01  # BUTTON_EVENT_PRESS

  on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - logger.log: "Button 0 double press"
        # Using the new bthome.button_event action
        - bthome.button_event:
            id: bthome_broadcaster
            index: 0
            action: 0x02  # BUTTON_EVENT_DOUBLE_PRESS

- platform: gpio
  pin:
    number: GPIO1
    inverted: true
    mode:
      input: true
      pullup: true
  name: "Button 1"
  on_press:
    then:
      - logger.log: "Button 1 pressed"
      # Using the new bthome.button_event action
      - bthome.button_event:
          id: bthome_broadcaster
          index: 1
          action: 0x01  # BUTTON_EVENT_PRESS

# Example sensor with dimmer control
sensor:
- platform: rotary_encoder
  name: "Rotary Encoder"
  id: rotary
  pin_a: GPIO2
  pin_b: GPIO3
  on_value:
    then:
      - lambda: |-
          static float last_value = 0;
          float delta = x - last_value;
          last_value = x;
          
          int8_t steps = (int8_t)delta;
          if (steps != 0) {
            // Direct C++ call for simplicity in lambda
            id(bthome_broadcaster)->send_dim_event(0, steps);
          }

# Example API endpoints demonstrating the new actions
api:
  services:
    - service: send_button_event
      variables:
        button_index: int
        event_type: int
      then:
        - logger.log:
            format: "API: sending button event index=%d type=0x%02X"
            args: ['button_index', 'event_type']
        # Using the new bthome.button_event action
        - bthome.button_event:
            id: bthome_broadcaster
            index: !lambda "return button_index;"
            action: !lambda "return event_type;"
    
    - service: send_dim_event
      variables:
        dimmer_index: int
        steps: int
      then:
        - logger.log:
            format: "API: sending dimmer event index=%d steps=%d"
            args: ['dimmer_index', 'steps']
        # Using the new bthome.dim_event action
        - bthome.dim_event:
            id: bthome_broadcaster
            index: !lambda "return dimmer_index;"
            steps: !lambda "return steps;"

# Button event type constants (BTHome v2 spec):
# BUTTON_EVENT_NONE           = 0x00  # Special: no event (for multi-button advertisements)
# BUTTON_EVENT_PRESS          = 0x01  # Single press
# BUTTON_EVENT_DOUBLE_PRESS   = 0x02  # Double press
# BUTTON_EVENT_TRIPLE_PRESS   = 0x03  # Triple press
# BUTTON_EVENT_LONG_PRESS     = 0x04  # Long press
# BUTTON_EVENT_LONG_DOUBLE_PRESS = 0x05  # Long double press
# BUTTON_EVENT_LONG_TRIPLE_PRESS = 0x06  # Long triple press
# BUTTON_EVENT_HOLD_PRESS     = 0x80  # Hold/continuous press (now works for any button!)
#
# Examples:
#   Single button 0 press:           send_button_event(0, 0x01)
#   Single button 1 double press:    send_button_event(1, 0x02)
#   Button 0 press + Button 1 long:  send_button_events({0x01, 0x04})
#   Only button 1 press:             send_button_events({0x00, 0x01})

