# BTHome Button and Dimmer Event Example (Unified Event API)
# Demonstrates how to send button and dimmer events via BLE using BTHome v2 protocol
# Compatible with Home Assistant's BTHome integration
#
# BTHome v2 Spec: https://bthome.io/format/
# Multiple buttons are represented by multiple sequential 0x3A objects
# The order determines button index (0=first, 1=second, etc.)

esphome:
  name: bthome-button-dimmer
  friendly_name: BTHome Button Dimmer
  on_boot:
    - priority: -100
      then:
        - logger.log: "BTHome ready with unified event API."

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

external_components:
  - source:
      type: local
      path: components
    components: [ bthome ]

# Required for ESP32 BLE
esp32_ble:
  id: ble

# BTHome configuration
bthome:
  id: bthome_transmitter
  min_interval: 5s
  max_interval: 10s
  tx_power: 0
  trigger_based: true  # For button/event-based devices
  max_events: 2

# Example button that triggers BTHome button events using actions
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Button 0"
    on_press:
      then:
        - logger.log: "Button 0 pressed - sending BTHome button event"
        # Use bthome.button_event action in shortcut form
        - bthome.button_event: press

    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Button 0 double press"
          # Use bthome.button_event action with lambda
          - bthome.button_event:
              index: 0
              action: !lambda |-
                return esphome::bthome::BUTTON_EVENT_DOUBLE_PRESS;

  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Button 1"
    on_press:
      then:
        - logger.log: "Button 1 pressed"
        # Use bthome.button_event action
        - bthome.button_event:
            index: 1
            action: 0x01  # use numeric value

# Example sensor with dimmer control
sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    id: rotary
    pin_a: GPIO18
    pin_b: GPIO19
    on_clockwise:
      # Shortcut form for dimmer event
      - bthome.dim_event: 1
    on_anticlockwise:
      # Full mapping for dimmer event
      - bthome.dim_event:
          index: 0
          steps: -1
      # Alternative: use lambda syntax for steps (runs after the previous action)
      - bthome.dim_event:
          steps: !lambda return -1;
